#!/usr/bin/env python3
"""Off-chain reference signer for src/BN254.sol.

Implements EXACTLY the hash-to-curve in BN254.hashToG1 — same DST, same
try-and-increment, same canonical-root rule. If this file and the Solidity
disagree, signatures will not verify, so this doubles as the specification
of the wire format.

Emits Solidity test vectors on stdout.
"""
from Crypto.Hash import keccak
from py_ecc.optimized_bn128 import (
    G1, G2, field_modulus as P, curve_order as R,
    multiply, normalize, neg, add, pairing, FQ, FQ2, is_on_curve, b2,
)

DST = b"SORTITION-BLS-BN254-KECCAK-TAI-G1-v1"
B = 3


def keccak256(data: bytes) -> bytes:
    k = keccak.new(digest_bits=256)
    k.update(data)
    return k.digest()


def hash_to_g1(message: bytes):
    """Try-and-increment. Mirrors BN254.hashToG1 exactly."""
    x = int.from_bytes(keccak256(DST + message), "big") % P
    for _ in range(256):
        y2 = (pow(x, 3, P) + B) % P
        y = pow(y2, (P + 1) // 4, P)
        if (y * y) % P == y2:
            if y != 0:
                neg_y = P - y
                return (x, min(y, neg_y))
        x = (x + 1) % P
    raise RuntimeError("hash to curve failed")


def to_pt(xy):
    return (FQ(xy[0]), FQ(xy[1]), FQ.one())


def sign(sk: int, message: bytes):
    h = to_pt(hash_to_g1(message))
    return normalize(multiply(h, sk))


def pubkey(sk: int):
    return normalize(multiply(G2, sk))


def verify_offchain(pk, message: bytes, sig) -> bool:
    """e(sig, G2) * e(-H(m), pk) == 1, computed independently of any chain."""
    h = to_pt(hash_to_g1(message))
    sig_pt = (FQ(sig[0]), FQ(sig[1]), FQ.one())
    pk_pt = (pk[0], pk[1], FQ2.one())
    lhs = pairing(G2, sig_pt)
    rhs = pairing(pk_pt, neg(h))
    return lhs * rhs == lhs.one()


def sol_g1(name, pt):
    return f"    BN254.G1Point memory {name} = BN254.G1Point({pt[0]}, {pt[1]});"


def sol_g2(name, pt):
    x, y = pt[0], pt[1]
    return (f"    BN254.G2Point memory {name} = BN254.G2Point(\n"
            f"        {x.coeffs[0]},\n        {x.coeffs[1]},\n"
            f"        {y.coeffs[0]},\n        {y.coeffs[1]}\n    );")


if __name__ == "__main__":
    SK = 0x2a1f5b3c9d8e7f60415263748596a7b8c9d0e1f2031425364758697a8b9c0d1e % R
    MSG = b"sortition stage 1 known-good vector"

    pk = pubkey(SK)
    sig = sign(SK, MSG)
    h = hash_to_g1(MSG)

    assert is_on_curve(to_pt(h), FQ(B)), "H(m) not on curve"
    assert is_on_curve(to_pt(sig), FQ(B)), "signature not on curve"
    assert normalize(multiply(to_pt(sig), R))[0] is not None
    ok = verify_offchain(pk, MSG, sig)
    assert ok, "reference signature does not verify off-chain"

    print("// Generated by tools/bls_reference.py — do not hand-edit.")
    print(f"// message  = {MSG!r}")
    print(f"// secret   = {hex(SK)}  (test key, public on purpose, never used on chain)")
    print(f"// verified off-chain with py_ecc pairing: {ok}")
    print()
    print(f'    bytes constant MESSAGE = "{MSG.decode()}";')
    print(sol_g2("pk", pk))
    print(sol_g1("sig", sig))
    print(sol_g1("hm", h))
    print()
    print(f"// H(m) took {'?'} iterations; x offset from keccak:")
    x0 = int.from_bytes(keccak256(DST + MSG), "big") % P
    print(f"//   keccak x0 = {x0}")
    print(f"//   final   x = {h[0]}   (delta {(h[0] - x0) % P})")
